### ISSUE TITLE
Dead or Alive?

### ISSUE THREAD

**Issue by tiptronic** [iwaxx/blog#15]
Is this app (Debookee) dead?  

All silent here on the webpage, FB, X....

**Comment by debookee** [comment]
Hey there ! Well, we're silent, but working in background!

To be honest, Debookee has problem with TLS decryption since an Apple bug 2 years ago, and the support still haven't worked on the case yet. Cf #13 

Also, some users reported problems with WM module on M2 & M3, but we couldn't reproduce them yet.

What's your problematic ? Did you try free trial ?

**Comment by debookee** [comment]
Close the issue without answer after 2 weeks, but don't hesitate to contact us by email : support@iwaxx.com
